# Generated by Django 4.0.5 on 2022-06-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Описание')),
                ('status', models.CharField(default='New', max_length=100, verbose_name='Статус')),
                ('deadline', models.DateField(verbose_name='Дедлайн')),
            ],
        ),
    ]
