# Generated by Django 4.0.5 on 2022-06-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_todolist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='deadline',
            field=models.DateField(null=True, verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], default=('new', 'Новая'), max_length=20, verbose_name='Статус'),
        ),
    ]
